### ISSUE TITLE
Grant repo access to rest of team

### ISSUE THREAD

**Issue by jseppi** [18F/calc-analysis#2]
Not quite clear how this gets accomplished, maybe through #admins-github in Slack. If access here should mirror [calc](https://github.com/18F/calc) then the "oasis" and "core-admins" teams should have admin permissions.

**Comment by toolness** [comment]
Ok, I just looked at CALC's settings and the `oasis` team has full admin access, while the `consulting` team has write access.  I just applied those settings to this repo, along with the existing setting of `18F` having write access too.
